name: mkhouse-jetbrains-hub

x-common-props: &common-props
  restart: "unless-stopped"
  dns:
    - 1.1.1.1
    - 4.4.4.4
  environment:
    PUID: "1000"
    PGID: "1000"
    TZ: "America/Sao_Paulo"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  extra_hosts:
      - host.docker.internal:host-gateway
  networks:
    stack-net:

services:

  mkhouse-jetbrains-hub-db:
    <<: *common-props
    image: "postgres:16-alpine"
    container_name: "mkhouse-jetbrains-hub-db"
    hostname: "mkhouse-jetbrains-hub-db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - mkhouse-jetbrainshub-db-data:/var/lib/postgresql/data
    networks:
      mkhouse-db-net:

  mkhouse-jetbrains-hub:
    image:  jetbrains/hub:2024.3.57595"
    container_name: "mkhouse-jetbrains-hub"
    hostname: "mkhouse-jetbrains-hub"
    <<: *common-props
    volumes:
      - "mkhouse-jetbrainshub-data:/opt/hub/data"
      - "mkhouse-jetbrainshub-conf:/opt/hub/conf"
    networks:
      mkhouse-jetbrains-net:
      mkhouse-vpc-net:

networks:
  stack-net:
    driver: "bridge"
  mkhouse-jetbrains-net:
    external: true
  mkhouse-vpc-net:
    external: true
  mkhouse-db-net:
    external: true

volumes:
  mkhouse-jetbrainshub-db-data:
    external: true
  mkhouse-jetbrainshub-data:
    external: true
  mkhouse-jetbrainshub-conf:
    external: true
