---
- name: "Publish JetBrains Hub project to remote nodes"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  vars:
    JETBRAINSHUB_PROJECT: "{{ JETBRAINSHUB_PROJECT }}"

  tasks:

    - name: "Check if project directory exists"
      stat:
        path: "{{ JETBRAINSHUB_PROJECT }}"
      register: "project_dir"

    - name: "Create a timestamp variable"
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      when: |
        project_dir.stat.exists

    - name: "Create backup directory if it doesn't exist"
      file:
        path: "{{ JETBRAINSHUB_PROJECT }}_backup"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      when: |
        project_dir.stat.exists

    - name: "Create a zip backup of the JetBrains Hub project"
      archive:
        path: "{{ JETBRAINSHUB_PROJECT }}"
        dest: "{{ JETBRAINSHUB_PROJECT }}_backup/jetbrainshub_backup_{{ timestamp }}.zip"
        format: "zip"
      when: |
        project_dir.stat.exists

- name: "Clean and publish JetBrains Hub project to remote nodes"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  vars:
    JETBRAINSHUB_PROJECT: "{{ JETBRAINSHUB_PROJECT }}"

  tasks:

    - name: "Ensure destination directory exists"
      file:
        path: "{{ JETBRAINSHUB_PROJECT }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Clean the destination directory"
      command: |
        rm -rf {{ JETBRAINSHUB_PROJECT }}/* {{ JETBRAINSHUB_PROJECT }}/.[!.]* {{ JETBRAINSHUB_PROJECT }}/..?*
      ignore_errors: true

    - name: "Copy JetBrains Hub project to remote nodes"
      synchronize:
        src: "{{ ANSIBLE_PROJECT }}/_dropfolder/jetbrains-hub/"
        dest: "{{ JETBRAINSHUB_PROJECT }}"
        delete: true
        recursive: true
        rsync_opts:
          - "--chmod=D0755,F0644"

    - name: "Set permissions on JetBrains Hub project files"
      file:
        path: "{{ JETBRAINSHUB_PROJECT }}"
        state: "directory"
        recurse: true
        owner: "root"
        group: "root"
        mode: "0755"

- name: "Install Docker"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  tasks:

    - name: "Check if Docker is already installed"
      command: "docker --version"
      register: "docker_installed"
      ignore_errors: true

    - name: "Update package list (Debian/Ubuntu)"
      apt:
        update_cache: true
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Install required packages (Debian/Ubuntu)"
      apt:
        name:
          - "apt-transport-https"
          - "ca-certificates"
          - "curl"
          - "software-properties-common"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Add Docker's official GPG key (Debian/Ubuntu)"
      apt_key:
        url: "https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}/gpg"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Add Docker repository (Debian/Ubuntu)"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }} $(lsb_release -cs) stable"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Update package list after adding Docker repository (Debian/Ubuntu)"
      apt:
        update_cache: true
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Install Docker (Debian/Ubuntu)"
      apt:
        name: "docker-ce"
        state: "present"
      when: |
        ansible_os_family == "Debian" and docker_installed.failed

    - name: "Update package list (Fedora)"
      dnf:
        update_cache: true
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Install required packages (Fedora)"
      dnf:
        name:
          - "dnf-plugins-core"
        state: "present"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Add Docker repository (Fedora)"
      command: "dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Install Docker (Fedora)"
      dnf:
        name: "docker-ce"
        state: "present"
      when: |
        ansible_os_family == "RedHat" and docker_installed.failed

    - name: "Ensure Docker service is running and enabled"
      service:
        name: "docker"
        state: "started"
        enabled: "true"
      when: |
        docker_installed.failed

    - name: "Add current user to docker group"
      user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: "true"
      when: |
        docker_installed.failed

- name: "Deploy JetBrains Hub"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true
  vars:
    JETBRAINSHUB_PROJECT: "{{ JETBRAINSHUB_PROJECT }}"

  tasks:

    - name: "Ensure Docker networks exist"
      mkh_ensure_docker_network:
        networks:
          - name: "mkhouse-vpc-net"
          - name: "mkhouse-jetbrains-net"
          - name: "mkhouse-db-net"

    - name: "Ensure Docker volumes meet expectations"
      mkh_ensure_docker_volume:
        volumes:
          - name: "mkhouse-jetbrainshub-data"
            device:
              path: "/mkh/srv/mkhouse/jetbrainshub-data"
              permissions: '0755'
              puid: '1000'
              pgid: '1000'
          - name: "mkhouse-jetbrainshub-conf"
            device:
              path: "/mkh/srv/mkhouse/jetbrainshub-conf"
              permissions: '0755'
              puid: '1000'
              pgid: '1000'
          - name: "mkhouse-jetbrainshub-db-data"
            device:
              path: "/mkh/srv/mkhouse/jetbrainshub-db-data"
              permissions: '0755'
              puid: '1000'
              pgid: '1000'

    - name: "Remove existing .env file if it exists"
      file:
        path: "{{ JETBRAINSHUB_PROJECT }}/.env"
        state: "absent"

    - name: "Generate .env file with token"
      copy:
        dest: "{{ JETBRAINSHUB_PROJECT }}/.env"
        content: |
          POSTGRES_DB={{ JBHUB_DATABASE_NAME }}
          POSTGRES_USER={{ JBHUB_DATABASE_USER }}
          POSTGRES_PASSWORD={{ JBHUB_DATABASE_PASSWORD }}

    - name: "Pull Docker Compose services"
      command: |
        docker compose pull
      args:
        chdir: "{{ JETBRAINSHUB_PROJECT }}"

    - name: "Stop Docker Compose services"
      command: |
        docker compose down
      args:
        chdir: "{{ JETBRAINSHUB_PROJECT }}"

    - name: Set realpath for docker directory
      set_fact:
        docker_realpath: "{{ lookup('pipe', 'realpath ' + playbook_dir + '/../../docker') }}"

    - name: Copy hub-config to mkhouse-jetbrainshub-conf volume
      command: >
        docker run --rm
        -v mkhouse-jetbrainshub-conf:/target
        -v {{ docker_realpath }}:/source
        alpine
        sh -c "cp /source/hub-config.properties /target/"

    - name: "Start Docker Compose services"
      command: |
        docker compose up -d --force-recreate --remove-orphans --build
      args:
        chdir: "{{ JETBRAINSHUB_PROJECT }}"

    - name: "Prune unused Docker images"
      command: |
        docker image prune --force

- name: "Release JetBrains Hub"
  hosts: "tankian.mkh"
  become: true
  any_errors_fatal: true

  tasks:

    - name: "Ensure Cloudflared Tunnels"
      mkh_ensure_cfd_tunnel:
        account_id: "{{ CF_ACCOUNT_ID }}"
        api_token: "{{ CF_TUNNEL_API_TOKEN }}"
        tunnel_name: "{{ CF_TUNNEL_NAME }}"
        private_service: "{{ CF_SERVICE }}"
        public_hostname: "{{ CF_HOSTNAME }}"
        zone_id: "{{ CF_ZONE_ID }}"
