name: "Deploy JetBrains Hub"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches:
      - "main"

jobs:
  deploy-rabbitmq:
    name: "Deploy JetBrains Hub"
    runs-on:
      - "self-hosted"
    env:
      ANSIBLE_PROJECT: "${{ vars.ANSIBLE_PROJECT }}"
      JETBRAINSHUB_PROJECT: "${{ vars.JETBRAINSHUB_PROJECT }}"
      CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
      CF_TUNNEL_API_TOKEN: "${{ secrets.CF_TUNNEL_API_TOKEN }}"
      CF_TUNNEL_NAME: "${{ vars.CF_TUNNEL_NAME }}"
      CF_SERVICE: "${{ vars.CF_SERVICE }}"
      CF_HOSTNAME: "${{ vars.CF_HOSTNAME }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Copy project to dropfolder"
        run: |
          sudo rm -rf ${ANSIBLE_PROJECT}/_dropfolder/jetbrains-hub/*
          sudo mkdir -p ${ANSIBLE_PROJECT}/_dropfolder/jetbrains-hub
          sudo chmod 0755 ${ANSIBLE_PROJECT}/_dropfolder/jetbrains-hub
          sudo cp -r ./docker/* ${ANSIBLE_PROJECT}/_dropfolder/jetbrains-hub/
      - name: "Run Ansible Playbook"
        run: |
          cd ${ANSIBLE_PROJECT}
          ansible-playbook ${GITHUB_WORKSPACE}/ansible/playbooks/deploy-jetbrains-hub.yml \
            -v \
            -i ./inventory/hosts.ini \
            -e ANSIBLE_PROJECT=${ANSIBLE_PROJECT} \
            -e JETBRAINSHUB_PROJECT=${JETBRAINSHUB_PROJECT} \
            -e CF_ACCOUNT_ID=${CF_ACCOUNT_ID} \
            -e CF_TUNNEL_API_TOKEN=${CF_TUNNEL_API_TOKEN} \
            -e CF_TUNNEL_NAME=${CF_TUNNEL_NAME} \
            -e CF_SERVICE=${CF_SERVICE} \
            -e CF_HOSTNAME=${CF_HOSTNAME}
